services:
  temporal:
    image: temporalio/temporal:latest
    command:
      - server
      - start-dev
      - --ip
      - '0.0.0.0'
      - --db-filename
      - /data/temporal.db
    ports:
      - '7233:7233' # gRPC
      - '8233:8233' # Web UI
    volumes:
      - temporal-data:/data

volumes:
  temporal-data:
