services:
  init-temporal-data:
    image: busybox
    volumes:
      - temporal-data:/data
    command: chown -R 1000:1000 /data

  temporal:
    image: temporalio/temporal:latest
    depends_on:
      init-temporal-data:
        condition: service_completed_successfully
    command:
      - server
      - start-dev
      - --ip
      - '0.0.0.0'
      - --db-filename
      - /data/temporal.db
    ports:
      - '7233:7233' # gRPC
      - '8233:8233' # Web UI
    volumes:
      - temporal-data:/data

volumes:
  temporal-data:
