packages:
  - apps/*
  - packages/*
  - packages/fastify/*
  - tooling/*
  - tooling/templates/*

catalog:
  zod: ^4.1.13

catalogs:
  testing:
    '@vitest/coverage-v8': ^4.0.14
    vitest: ^4.0.14
  tooling:
    '@biomejs/biome': 2.3.8
    '@types/node': ^24.10.1
    tsdown: ^0.16.7
    tsx: ^4.20.6
    typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - protobufjs
