packages:
  - apps/*
  - packages/*
  - packages/fastify/*
  - tooling/*
  - tooling/templates/*

catalog:
  zod: ^4.1.13

catalogs:
  testing:
    '@vitest/coverage-v8': ^4.0.15
    vitest: ^4.0.15
  tooling:
    oxlint: ^1.39.0
    oxlint-tsgolint: ^0.11.1
    oxfmt: ^0.24.0
    '@types/node': ^24.10.1
    tsdown: ^0.17.2
    tsx: ^4.21.0
    '@typescript/native-preview': ^7.0.0-dev

onlyBuiltDependencies:
  - esbuild
  - protobufjs
