packages:
  - apps/*
  - packages/*
  - tooling/*
  - tooling/templates/*
  
catalog:
  zod: ^4.1.12
  
catalogs:
  tooling:
    "@biomejs/biome": 2.3.4
    "@types/node": ^24.10.0
    tsdown: ^0.16.1
    tsx: ^4.20.6
    typescript: ^5.9.3
  
  testing:
    "@vitest/coverage-v8": ^4.0.8
    vitest: ^4.0.8
    

onlyBuiltDependencies:
  - esbuild
