packages:
  - apps/*
  - packages/*
  - packages/fastify/*
  - tooling/*
  - tooling/templates/*

catalog:
  zod: ^4.1.13

catalogs:
  testing:
    '@vitest/coverage-v8': ^4.0.15
    vitest: ^4.0.15
  tooling:
    '@biomejs/biome': 2.3.8
    '@types/node': ^24.10.1
    tsdown: ^0.17.2
    tsx: ^4.21.0
    typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - protobufjs
