packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  tooling:
    '@biomejs/biome': 2.3.4
    '@types/node': ^22.19.0
    tsdown: ^0.15.12
    tsx: ^4.20.6
    typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
