packages:
  - apps/*
  - packages/*
  - packages/fastify/*
  - tooling/*
  - tooling/templates/*

catalog:
  zod: ^4.3.5
  fastify: 5.6.2

catalogs:
  testing:
    '@vitest/coverage-v8': ^4.0.17
    vitest: ^4.0.17
  tooling:
    oxlint: ^1.39.0
    oxlint-tsgolint: ^0.11.1
    oxfmt: ^0.24.0
    '@types/node': ^24.10.1
    tsdown: ^0.19.0
    tsx: ^4.21.0
    '@typescript/native-preview': ^7.0.0-dev.20260118.1

onlyBuiltDependencies:
  - esbuild
  - protobufjs
