packages:
  - apps/*
  - packages/*
  - packages/fastify/*
  - tooling/*
  - tooling/templates/*

catalog:
  zod: ^4.3.6
  fastify: 5.8.1

catalogs:
  testing:
    '@vitest/coverage-v8': ^4.0.18
    vitest: ^4.0.18
  tooling:
    oxlint: ^1.51.0
    oxlint-tsgolint: ^0.16.0
    oxfmt: ^0.36.0
    '@types/node': ^24.10.1
    tsdown: ^0.21.0
    tsx: ^4.21.0
    '@typescript/native-preview': ^7.0.0-dev.20260307.1

onlyBuiltDependencies:
  - esbuild
  - protobufjs
